blank_issues_enabled: false
contact_links:
  - name: StarKingdoms Discord
    url: https://discord.gg/YNZKjMfmBc
    about: If you are having issues with the game or have other minor issues, come ask us on our Discord server!
